# -*- coding: utf-8 -*-
"""python sif200192.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Fp13qHbQGP0Qyq3Ql1AZnbhTW8m3Yqc
"""

correct = 0
print("Welcome to the Quiz world")
print()
input("Enter your name : ")
print()
print("You will be Getting 4 Questions, Answer them with Yes or NO")
print()
answer1=input("1.Is the Earth the largest planet on the Solar System? ").lower()
if answer1 == "no":
    print("Correct")
    correct =correct+1
    print("Your Score :",correct )
else:
    print("Incorrect answer")
    print("Your Score :",correct )

print()
answer2=input("2.Is Sri lanka the biggest country on asia? ").lower()
if answer2 == "no":
    print("Correct")
    correct =correct+1
    print("Your Score :",correct )
else:
    print("Incorrect answer")
    print("Your Score :",correct )

print()
answer3=input("3.Sri lanka is a Island? ").lower()
if answer3 == "yes":
    print("correct")
    correct =correct+1
    print("Your Score : ",correct )
else:
    print("Incorrect answer")
    print("Your Score :",correct )

print()
answer4=input("4.Is the Largest Ocean in the world is Pasific").lower()
if answer3 == "yes":
    print("correct")
    correct =correct+1
    print("Your Score : ",correct )
else:
    print("Incorrect answer")
    print("Your Score :",correct )

print()
print("Your Final Score is : ",correct)
if correct == 1:
  print("You got a Bronze Medal")
elif correct == 2:
  print("You got a Silver Medal")
elif correct ==3 :
  print("you got a Gold Medal")
else:
  print("You Got Nothing ")

print()
print("thank you for Playing with us! come again")
